const { compile } = require("..");
// requires Node v15.7 or above
const assert = require('assert/strict');

let output = compile("let a = 1");
assert.strictEqual(output, "// Generated by uwu compiler v0.0\nlet a = 1; \n");
